version: "3"

x-db-environment: &db-environment
  DB_USERNAME: test
  DB_PASSWORD: test
  DB_HOST: mysql
  DB_NAME: ti

services:

  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ti
    ports:
      - 3306:3306
    restart: unless-stopped

  datagenerate:
    build: ./dataGenerate
    depends_on:
      - mysql
    environment:
      <<: *db-environment
    restart: on-failure
